
import { CompanyDetails, EmployeeData, EmployeeType } from './types';

export const initialCompanyDetails: CompanyDetails = {
  name: 'VS MUSIC STUDIO',
  address: 'Via Michelangelo Buonarroti, 15 - 20852 Villasanta (MB)',
  fiscalCode: 'SLVVCN83H30G942V',
  paymentDateDay: 27,
};

export const initialEmployeeData: EmployeeData[] = [
  {
    id: 'EG001',
    matricola: 'EG001',
    name: 'Eleonora Galli',
    qualifica: 'Head of Marketing',
    type: EmployeeType.HUMAN,
    codiceFiscale: 'GLLNR87E45F205K',
    ccnl: 'Commercio - 4° Livello - Impiegato',
    baseOreLavorateStandard: 168,
    baseGiorniLavoroStandard: 21,
    ticketRestaurantPerDay: 7,
    competenzeItemsOriginal: [
      { description: 'Stipendio Base Mensile', amount: 2916.67 },
      { description: 'Scatti Anzianità', amount: 0.00 },
      { description: 'Superminimo', amount: 0.00 },
    ],
    totaleCompetenzeOriginal: 2916.67,
    trattenuteItemsOriginal: [
      { description: 'IRPEF Lorda', amount: 670.83 },
      { description: 'Detrazione Lavoro Dipendente', amount: -91.60 },
      { description: 'IRPEF Netta', amount: 579.23, isSubTotal: true },
      { description: 'Addizionale Regionale', amount: 43.75 },
      { description: 'Addizionale Comunale', amount: 23.33 },
      { description: 'Contributi INPS (9,19%)', amount: 268.02 },
    ],
    totaleTrattenuteOriginal: 914.33,
    benefitsAndRimborsiItemsOriginal: [
      { description: 'Ticket Restaurant', amount: 147.00, details: '€7/giorno x 21 giorni' },
      { description: 'Strumenti SEO Premium', amount: 33.33, details: '/mese' },
      { description: 'Bonus Articoli', amount: 100.00 },
      { description: 'Smart Working', details: '100%' },
      { description: 'Corsi Copywriting inclusi' },
    ],
    nettoInBustaOriginal: 2100.00,
  },
  {
    id: 'CP002',
    matricola: 'CP002',
    name: 'Chiara Pellegrino',
    qualifica: 'Press Officer',
    type: EmployeeType.HUMAN,
    codiceFiscale: 'PLLCHR93D56D969S',
    ccnl: 'Commercio - 3° Livello - Impiegato Senior',
    baseOreLavorateStandard: 168,
    baseGiorniLavoroStandard: 21,
    ticketRestaurantPerDay: 8,
    competenzeItemsOriginal: [
      { description: 'Stipendio Base Mensile', amount: 2583.33 },
      { description: 'Bonus PR Mensile', amount: 100.00 },
    ],
    totaleCompetenzeOriginal: 2683.33,
    trattenuteItemsOriginal: [
      { description: 'IRPEF Lorda', amount: 617.17 },
      { description: 'Detrazione Lavoro Dipendente', amount: -91.60 },
      { description: 'IRPEF Netta', amount: 525.57, isSubTotal: true },
      { description: 'Addizionale Regionale', amount: 40.25 },
      { description: 'Addizionale Comunale', amount: 21.47 },
      { description: 'Contributi INPS (9,19%)', amount: 246.62 },
    ],
    totaleTrattenuteOriginal: 833.91,
    benefitsAndRimborsiItemsOriginal: [
      { description: 'Ticket Restaurant', amount: 168.00, details: '€8/giorno x 21 giorni' },
      { description: 'Laptop Aziendale' },
      { description: 'Rimborso Trasferte Stampa' },
      { description: 'Eventi di Networking' },
      { description: 'Bonus PR', amount: 1200.00, details: '/anno' },
    ],
    nettoInBustaOriginal: 1900.00,
  },
  {
    id: 'AC003',
    matricola: 'AC003-CYBORG',
    name: 'Alice Cyberdiva',
    qualifica: 'Cyborg Studio Assistant',
    type: EmployeeType.CYBORG,
    serialNumber: 'CYB-2024-003',
    ccnl: 'Contratto Speciale - Assistente Robotico',
    uptimePercent: 99.8,
    competenzeItemsOriginal: [
      { description: 'Stipendio Base Mensile', amount: 2000.00 },
      { description: 'Bonus Interazione Clienti', amount: 41.67 },
    ],
    totaleCompetenzeOriginal: 2041.67,
    trattenuteItemsOriginal: [
      { description: 'IRPEF Cyborg (23%)', amount: 469.58 },
      { description: 'Contributi Fondo Cyborg', amount: 102.08 },
      { description: 'Tassa Tecnologica Regionale', amount: 30.63 },
    ],
    totaleTrattenuteOriginal: 602.29,
    benefitsTecnologiciOriginal: [
      { description: 'Fornitura Energetica', amount: 150.00, details: '/mese' },
      { description: 'Manutenzione Hardware', amount: 166.67, details: '/mese (€2.000/anno)' },
      { description: 'Aggiornamenti Software', amount: 66.67, details: '/mese (€800/anno)' },
      { description: 'Assicurazione Tecnologica' },
      { description: 'Copertura Incidenti' },
    ],
    nettoInCircuitiOriginal: 1550.00,
  },
   {
    id: 'GE004',
    matricola: 'GE004',
    name: 'Giorgia Esposito',
    qualifica: 'Art Director',
    type: EmployeeType.HUMAN,
    codiceFiscale: 'SPTGRG89M48F839M',
    ccnl: 'Commercio - 3° Livello - Impiegato Senior',
    baseOreLavorateStandard: 168,
    baseGiorniLavoroStandard: 21,
    ticketRestaurantPerDay: 8,
    competenzeItemsOriginal: [
      { description: 'Stipendio Base Mensile', amount: 2666.67 },
    ],
    totaleCompetenzeOriginal: 2666.67,
    trattenuteItemsOriginal: [
      { description: 'IRPEF Lorda', amount: 613.33 },
      { description: 'Detrazione Lavoro Dipendente', amount: -91.60 },
      { description: 'IRPEF Netta', amount: 521.73, isSubTotal: true },
      { description: 'Addizionale Regionale', amount: 40.00 },
      { description: 'Addizionale Comunale', amount: 21.33 },
      { description: 'Contributi INPS (9,19%)', amount: 245.04 },
    ],
    totaleTrattenuteOriginal: 828.10,
    benefitsAndRimborsiItemsOriginal: [
      { description: 'Ticket Restaurant', amount: 168.00, details: '€8/giorno x 21 giorni' },
      { description: 'Budget Software Adobe', amount: 50.00, details: '/mese (€600/anno)' },
      { description: 'MacBook Pro Aziendale' },
      { description: 'Orari Flessibili' },
      { description: 'Corsi Graphic Design inclusi' },
    ],
    nettoInBustaOriginal: 1950.00,
  },
  {
    id: 'MG005',
    matricola: 'MG005',
    name: 'Martina Gentile',
    qualifica: 'Studio Manager & CCO',
    type: EmployeeType.HUMAN,
    codiceFiscale: 'GNTMTN90B62H501R',
    ccnl: 'Commercio - 1° Livello - Quadro',
    baseOreLavorateStandard: 168,
    baseGiorniLavoroStandard: 21,
    ticketRestaurantPerDay: 8,
    competenzeItemsOriginal: [
      { description: 'Stipendio Base Mensile', amount: 3166.67 },
      { description: 'Bonus Management', amount: 200.00 },
      { description: 'Bonus Fedeltà (Mensile)', amount: 125.00 },
    ],
    totaleCompetenzeOriginal: 3491.67,
    trattenuteItemsOriginal: [
      { description: 'IRPEF Lorda (27%)', amount: 942.75 }, // Note: % here is informational
      { description: 'Detrazione Lavoro Dipendente', amount: -91.60 },
      { description: 'IRPEF Netta', amount: 851.15, isSubTotal: true },
      { description: 'Addizionale Regionale', amount: 52.38 },
      { description: 'Addizionale Comunale', amount: 27.93 },
      { description: 'Contributi INPS (9,19%)', amount: 320.86 },
    ],
    totaleTrattenuteOriginal: 1252.32,
    benefitsAndRimborsiItemsOriginal: [
      { description: 'Ticket Restaurant', amount: 168.00, details: '€8/giorno x 21 giorni' },
      { description: 'Auto Aziendale per Trasferte' },
      { description: 'Rimborso Spese Telefoniche', amount: 50.00, details: '/mese' },
      { description: 'Bonus Fedeltà', amount: 1500.00, details: '/anno' },
      { description: 'Responsabilità GDPR Compliance' },
    ],
    nettoInBustaOriginal: 2250.00,
  },
  {
    id: 'MD006',
    matricola: 'MD006',
    name: 'Monica De Angelis',
    qualifica: 'Creative Consultant',
    type: EmployeeType.HUMAN,
    codiceFiscale: 'DNGLMN88T52D612L',
    ccnl: 'Commercio - 4° Livello - Impiegato',
    baseOreLavorateStandard: 168,
    baseGiorniLavoroStandard: 21,
    ticketRestaurantPerDay: 7,
    competenzeItemsOriginal: [
      { description: 'Stipendio Base Mensile', amount: 2333.33 },
      { description: 'Bonus Creatività (Mensile)', amount: 83.33 },
    ],
    totaleCompetenzeOriginal: 2416.67,
    trattenuteItemsOriginal: [
      { description: 'IRPEF Lorda', amount: 555.83 },
      { description: 'Detrazione Lavoro Dipendente', amount: -91.60 },
      { description: 'IRPEF Netta', amount: 464.23, isSubTotal: true },
      { description: 'Addizionale Regionale', amount: 36.25 },
      { description: 'Addizionale Comunale', amount: 19.33 },
      { description: 'Contributi INPS (9,19%)', amount: 222.09 },
    ],
    totaleTrattenuteOriginal: 741.90,
    benefitsAndRimborsiItemsOriginal: [
      { description: 'Ticket Restaurant', amount: 147.00, details: '€7/giorno x 21 giorni' },
      { description: 'Bonus Creatività', amount: 1000.00, details: '/anno' },
      { description: 'Accesso Biblioteca e Risorse' },
      { description: 'Orari Completamente Flessibili' },
      { description: 'Opzione Part-time disponibile' },
    ],
    nettoInBustaOriginal: 1750.00,
  },
  {
    id: 'GM007',
    matricola: 'GM007',
    name: 'Giulia Morelli',
    qualifica: 'Social Media Manager',
    type: EmployeeType.HUMAN,
    codiceFiscale: 'MRLLGL92C43A944P',
    ccnl: 'Commercio - 4° Livello - Impiegato',
    baseOreLavorateStandard: 168,
    baseGiorniLavoroStandard: 21,
    ticketRestaurantPerDay: 7,
    competenzeItemsOriginal: [
      { description: 'Stipendio Base Mensile', amount: 2166.67 },
      { description: 'Bonus Engagement (Mensile)', amount: 66.67 },
    ],
    totaleCompetenzeOriginal: 2233.33,
    trattenuteItemsOriginal: [
      { description: 'IRPEF Lorda', amount: 513.67 },
      { description: 'Detrazione Lavoro Dipendente', amount: -91.60 },
      { description: 'IRPEF Netta', amount: 422.07, isSubTotal: true },
      { description: 'Addizionale Regionale', amount: 33.50 },
      { description: 'Addizionale Comunale', amount: 17.87 },
      { description: 'Contributi INPS (9,19%)', amount: 205.24 },
    ],
    totaleTrattenuteOriginal: 678.68,
    benefitsAndRimborsiItemsOriginal: [
      { description: 'Ticket Restaurant', amount: 147.00, details: '€7/giorno x 21 giorni' },
      { description: 'Budget Strumenti Social', amount: 41.67, details: '/mese (€500/anno)' },
      { description: 'iPhone Aziendale' },
      { description: 'Corsi Social Media Marketing inclusi' },
      { description: 'Bonus Engagement', amount: 800.00, details: '/anno' },
    ],
    nettoInBustaOriginal: 1650.00,
  },
  {
    id: 'VB008',
    matricola: 'VB008',
    name: 'Vittoria Benedetti',
    qualifica: 'Blogger & SEO Specialist',
    type: EmployeeType.HUMAN,
    codiceFiscale: 'BNDVTR91L55L781N',
    ccnl: 'Commercio - 4° Livello - Impiegato',
    baseOreLavorateStandard: 168,
    baseGiorniLavoroStandard: 21,
    ticketRestaurantPerDay: 7,
    competenzeItemsOriginal: [
      { description: 'Stipendio Base Mensile', amount: 2416.67 },
      { description: 'Bonus Performance Blog (Mensile)', amount: 50.00 },
    ],
    totaleCompetenzeOriginal: 2466.67,
    trattenuteItemsOriginal: [
      { description: 'IRPEF Lorda', amount: 567.33 },
      { description: 'Detrazione Lavoro Dipendente', amount: -91.60 },
      { description: 'IRPEF Netta', amount: 475.73, isSubTotal: true },
      { description: 'Addizionale Regionale', amount: 37.00 },
      { description: 'Addizionale Comunale', amount: 19.73 },
      { description: 'Contributi INPS (9,19%)', amount: 226.68 },
    ],
    totaleTrattenuteOriginal: 759.14,
    benefitsAndRimborsiItemsOriginal: [
      { description: 'Ticket Restaurant', amount: 147.00, details: '€7/giorno x 21 giorni' },
      { description: 'Budget Strumenti SEO', amount: 33.33, details: '/mese (€400/anno)' },
      { description: 'Smart Working 100%' },
      { description: 'Corsi Content Writing inclusi' },
      { description: 'Bonus Performance Blog', amount: 600.00, details: '/anno' },
    ],
    nettoInBustaOriginal: 1800.00,
  }
];
